# Build-time: Vite embute VITE_* no bundle — passar como --build-arg no compose/CI
FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_META_APP_ID=""
ARG VITE_PUBLIC_APP_URL=""
ARG VITE_META_OAUTH_REDIRECT_URI=""
ARG VITE_META_EMBEDDED_SIGNUP_CONFIG_ID=""
ARG VITE_META_GRAPH_VERSION=""
ARG VITE_META_EMBEDDED_TOKEN_REDIRECT_URI=""
ARG VITE_INTERNAL_HOOK_SECRET=""

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_META_APP_ID=$VITE_META_APP_ID
ENV VITE_PUBLIC_APP_URL=$VITE_PUBLIC_APP_URL
ENV VITE_META_OAUTH_REDIRECT_URI=$VITE_META_OAUTH_REDIRECT_URI
ENV VITE_META_EMBEDDED_SIGNUP_CONFIG_ID=$VITE_META_EMBEDDED_SIGNUP_CONFIG_ID
ENV VITE_META_GRAPH_VERSION=$VITE_META_GRAPH_VERSION
ENV VITE_META_EMBEDDED_TOKEN_REDIRECT_URI=$VITE_META_EMBEDDED_TOKEN_REDIRECT_URI
ENV VITE_INTERNAL_HOOK_SECRET=$VITE_INTERNAL_HOOK_SECRET

RUN npm run build

FROM nginx:1.27-alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD wget -qO- http://127.0.0.1/health || exit 1

CMD ["nginx", "-g", "daemon off;"]
